services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    build: .
    environment:
      - TZ=Europe/Madrid
      - N8N_PROTOCOL=https
      - N8N_SECURE_COOKIE=true
      - N8N_HOST=perism.ir
      - N8N_PORT=5678
      - WEBHOOK_URL=https://perism.ir:2083/
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./n8n-data/codes:/home/node/codes
      - shared_downloads:/home/node/shared_downloads # Added shared volume for n8n
    networks:
      - n8nnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
          - "2083:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - n8n
    networks:
      - n8nnet
      
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    volumes:
      - shared_downloads:/downloads # Changed to use the shared volume
    ports:
      - "127.0.0.1:8081:8081"   # Only accessible from localhost
    networks:
      - n8nnet

networks:
  n8nnet:
    driver: bridge

volumes: # Added volumes section
  shared_downloads: # Defined the shared volume
