version: '3.8'

services:
  n8n_service:
    build: .
    image: my-custom-n8n:latest
    container_name: n8n_service
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      # Mounts a local directory for n8n's persistent data.
      - ./n8n-data:/home/node/.n8n
      # Mounts a shared directory for MeTube downloads.
      - ./metube-downloads:/mnt/metube_downloads
      # CRITICAL: Mounts your SSL certificates (read-only).
      # The 'cert' directory MUST contain 'fullchain.pem' and 'privkey.pem'.
      - ./cert:/mnt/cert:ro
    environment:
      # Variables loaded from the .env file
      N8N_HOST: ${N8N_HOST}
      WEBHOOK_URL: ${WEBHOOK_URL}
      TZ: ${TZ}
      # Static variables for this service configuration
      N8N_PORT: 8443
      N8N_PROTOCOL: https
      N8N_SSL_CERT: /mnt/cert/fullchain.pem
      N8N_SSL_KEY: /mnt/cert/privkey.pem
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
    networks:
      - app_network

  metube_service:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube_service
    restart: unless-stopped
    expose:
      - "8081"
    volumes:
      # Shared volume for MeTube to save downloaded files.
      - ./metube-downloads:/downloads
      # Mount your YouTube cookies file (read-only) for authenticated downloads.
      # Ensure 'youtube-cookies.txt' exists in this directory.
      - ./youtube-cookies.txt:/config/youtube-cookies.txt:ro
    environment:
      # Variables loaded from the .env file
      UID: ${METUBE_UID}
      GID: ${METUBE_GID}
      TZ: ${TZ}
      # Static variables for this service configuration
      DOWNLOAD_DIR: /downloads
      # Tell MeTube to use the cookies file for YouTube authentication.
      YTDL_OPTIONS: '{"cookies": "/config/youtube-cookies.txt"}'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
